# charts/application/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interswitch-api.fullname" . }}
  labels:
    {{ include "interswitch-api.labels" . | nindent 4 }}
type: Opaque
data:
  db-connection: {{ .Values.secrets.dbConnection | b64enc }}
  api-key: {{ .Values.secrets.apiKey | b64enc }}
